
export const FETCH_SIMULATORS = "FETCH_SIMULATORS";
export type FETCH_SIMULATORS = typeof FETCH_SIMULATORS;



export const FETCH_SIMULATOR = "FETCH_SIMULATOR";
export type FETCH_SIMULATOR= typeof FETCH_SIMULATOR;
