
export const FETCH_SIMULATORS = "FETCH_SIMULATORS";
export type FETCH_SIMULATORS = typeof FETCH_SIMULATORS;

export const RECIEVE_SIMULATORS = "RECIEVE_SIMUALTORS";
export type RECIEVE_SIMUALTORS= typeof RECIEVE_SIMULATORS;

export const ENVIRONMENT_CREATION_STARTED = "ENVIRONMENT_CREATION_STARTED";
export type ENVIRONMENT_CREATION_STARTED = typeof ENVIRONMENT_CREATION_STARTED;

export const ENVIRONMENT_CREATION_SUCCEEDED = "ENVIRONMENT_CREATION_SUCCEEDED";
export type ENVIRONMENT_CREATION_SUCCEEDED = typeof ENVIRONMENT_CREATION_SUCCEEDED;


export const ENVIRONMENT_CREATION_FAILED = "ENVIRONMENT_CREATION_FAILED";
export type ENVIRONMENT_CREATION_FAILED = typeof ENVIRONMENT_CREATION_FAILED;

export const RECIEVE_ENVIRONMENTS = "RECIEVE_ENVIRONMENTS";
export type RECIEVE_ENVIRONMENTS = typeof RECIEVE_ENVIRONMENTS;


export const SCENARIO_CREATION_STARTED = "SCENARIO_CREATION_STARTED";
export type SCENARIO_CREATION_STARTED = typeof SCENARIO_CREATION_STARTED;


export const SCENARIO_CREATION_SUCCEEDED = "SCENARIO_CREATION_SUCCEEDED";
export type SCENARIO_CREATION_SUCCEEDED = typeof SCENARIO_CREATION_SUCCEEDED;


export const SCENARIO_CREATION_FAILED = "SCENARIO_CREATION_FAILED";
export type SCENARIO_CREATION_FAILED = typeof SCENARIO_CREATION_FAILED;


export const SIMULATOR_FILE_UPLOAD_STARTED = "SIMULATOR_FILE_UPLOAD_STARTED";
export type SIMULATOR_FILE_UPLOAD_STARTED = typeof SIMULATOR_FILE_UPLOAD_STARTED;


export const SIMULATOR_FILE_UPLOAD_SUCCEEDED = "SIMULATOR_FILE_UPLOAD_SUCCEEDED";
export type SIMULATOR_FILE_UPLOAD_SUCCEEDED = typeof SIMULATOR_FILE_UPLOAD_SUCCEEDED;

export const SIMULATOR_FILE_UPLOAD_FAILED = "SIMULATOR_FILE_UPLOAD_FAILED";
export type SIMULATOR_FILE_UPLOAD_FAILED = typeof SIMULATOR_FILE_UPLOAD_FAILED;

export const SIMULATOR_CREATION_SUCCEEDED = "SIMULATOR_CREATION_SUCCEEDED";
export type SIMULATOR_CREATION_SUCCEEDED = typeof SIMULATOR_CREATION_SUCCEEDED;

export const SIMULATOR_CREATION_FAILED = "SIMULATOR_CREATION_FAILED";
export type SIMULATOR_CREATION_FAILED = typeof SIMULATOR_CREATION_FAILED;

export const SIMULATOR_CREATION_STARTED = "SIMULATOR_CREATION_STARTED";
export type SIMULATOR_CREATION_STARTED = typeof SIMULATOR_CREATION_STARTED;