
export const FETCH_SIMULATORS = "FETCH_SIMULATORS";
export type FETCH_SIMULATORS = typeof FETCH_SIMULATORS;


export const RECIEVE_SIMULATORS = "RECIEVE_SIMUALTORS";
export type RECIEVE_SIMUALTORS= typeof RECIEVE_SIMULATORS;

