import { ScenarioJSON } from "ditto-shared";

export const enum ScenariosActionTypes {
  SCENARIO_CREATION_SUCCEEDED = "SCENARIO_CREATION_SUCCEEDED",
  SCENARIO_CREATION_STARTED = "SCENARIO_CREATION_STARTED",
  SCENARIO_CREATION_FAILED = "SCENARIO_CREATION_FAILED",
  RECIEVE_SCENARIOS = "RECIEVE_SCENARIOS",
  SCENARIO_PLAY_FAILED = "SCENARIO_PLAY_FAILED",
  SCENARIO_PLAY_SUCCEEDED = "SCENARIO_PLAY_SUCCEEDED"
}

export interface ScenariosState{
    readonly all : ScenarioJSON[];
}