import { SimulatorDefinition } from "../../../../../simulations-manager/src/simulators/simulatorDefinition";

export const enum SimulatorActionTypes {
    FETCH_SIMULATORS = "FETCH_SIMULATORS",
    RECIEVE_SIMULATORS = "RECIEVE_SIMUALTORS",
    SIMULATOR_FILE_UPLOAD_STARTED = "SIMULATOR_FILE_UPLOAD_STARTED",
    SIMULATOR_FILE_UPLOAD_SUCCEEDED = "SIMULATOR_FILE_UPLOAD_SUCCEEDED",
    SIMULATOR_FILE_UPLOAD_FAILED = "SIMULATOR_FILE_UPLOAD_FAILED",
    SIMULATOR_CREATION_SUCCEEDED = "SIMULATOR_CREATION_SUCCEEDED",
    SIMULATOR_CREATION_FAILED = "SIMULATOR_CREATION_FAILED",
    SIMULATOR_CREATION_STARTED = "SIMULATOR_CREATION_STARTED"
}


export type SimulatorsState = SimulatorDefinition[];