enum EventTypes {
    SCENARIO_STARTED = "SCENARIO_STARTED",
    TEST_EXECUTION_STARTED = "TEST_EXECUTION_STARTED",
    STEP_STARTED = "STEP_STARTED",
    STEP_FINISHED = "STEP_FINISHED",
    ENVIRONMENT_EXECUTION_STARTED = "ENVIRONMENT_EXECUTION_STARTED",
    ENVIRONMENT_EXECUTION_FINISHED = "ENVIRONMENT_EXECUTION_FINISHED",
    ENVIRONMENT_EXECUTION_STATUS = "ENVIRONMENT_EXECUTION_STATUS"


}

export default EventTypes;